services:
  - type: web
    name: isizulu-corpus
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          name: isizulu-corpus-db
          type: postgresql
          property: connectionString
    healthCheckPath: /